org = "DragonOS-Community"
name = "dragonos"
description = "Coordination repository for the DragonOS-Community infra team"
bots = []

[access.teams]
kernel = "write"

[[branch-protections]]
pattern = 'master'

