on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@main
        with:
          fetch-depth: 50

      - name: Install Rust Stable
        run: |
          rustc -vV
          rustup update stable
          rustup default stable
          rustc -vV

      - name: Build the validation tool
        run: cargo build

      # - name: Validate the repository contents
      #   run: cargo run -- check --strict
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.github_token }}
      
      - name: Validate the repository contents
        run: cargo run -- check
      
      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run tests
        run: cargo test --workspace --all-features

      - name: Build the contents of the static API
        run: |
          cargo run -- static-api build
          echo "team-api.infra.dragonos.org.cn" > build/CNAME

     